### PR TITLE
Fix deprecated copy warnings

### PR DESCRIPTION
**Pull request by apolukhin**
All the implicit special member functions made explicit in this PR.
It fixes the compilation and test runs with `./b2 libs/concept_check/test/ cxxstd=2a,03,11,17,14 "cxxflags=-Werror=deprecated-copy" toolset=clang-13 -j4`

### CODE REVIEW

**Comment by jeking3** [comment]
@apolukhin could you rebase on develop to get a fresh CI run?  CI is passing.

**Comment by apolukhin** [comment]
@jeking3 done, CI is green

**Comment by apolukhin** [comment]
@jeking3 gentle reminder

**Comment by apolukhin** [comment]
@jeking3 gentle reminder

**Pull request merged**
